### ISSUE TITLE
Return types

### ISSUE THREAD

**Issue by lucaro** [vitrivr/cottontaildb-proto#2]
Some return types for methods of the `CottonDDL` service are not optimal:

- `ListSchemas` returns a single schema and not multiple
- `CreateSchema` and `DropSchema` don't return a status regarding the operations
- `CreateEntity`  returns a single entity rather than multiple
- `DropEntity`, `OptimizeEntity` and `TruncateEntity` don't return a status regarding the operations

**Comment by ppanopticon** [comment]
See latest commit: is this what you had in mind?

**Comment by lucaro** [comment]
Well, I guess `SuccessStatus` should contain some actual information about the success of the operation, rather than just a timestamp. How about a boolean for success and an error code/message in case of failure?

**Comment by ppanopticon** [comment]
There is nothing more to report than the timestamp: The fact that the method returns is a success indicator in and by itself. All the failure cases are handled by an exception being thrown.

Hence, a boolean for indicating success would be kind of redundant.

**Comment by lucaro** [comment]
And how is that exception being propagated to the caller?

**Comment by ppanopticon** [comment]
It‘s emmitted (and thrown) as a GRPC error using an appropriate GRPC error code. 

From what I understand, this is the recommended way of handling errors.

**Comment by lucaro** [comment]
So there is not supposed to be a way to communicate error messages?
